return {
    h = '/home/luca',
    ch = '/home/luca/.cache',
    cf = '/home/luca/.config',
    dt = '/home/luca/.local/share',
    sr = '/home/luca/.local/src',
    it = '/home/luca/.local/src/git',
    sc = '/home/luca/.local/bin',
    mn = '/mnt',
    dl = '/home/luca/Downloads',
    dm = '/home/luca/Documents',
    ms = '/home/luca/Music',
    pc = '/home/luca/Pictures',
    vd = '/home/luca/Videos',
    dot = '/home/luca/.local/share/stow/dots',
}